### ISSUE TITLE
Update README with current instructions?

### ISSUE THREAD

**Issue by duffn** [slack-ruby/slack-ruby-bot-server-sample#27]
I started a branch and working on updating the README but then wondered if:

- This was even necessary? `slack-ruby-bot-server` says to use the events sample now https://github.com/slack-ruby/slack-ruby-bot-server#make-your-own
- I didn't dig too deep, but wasn't even 100% sure how to set this up with a new Slack app or if it's possible any longer. I'm only mostly familiar with the events mechanism.

**Comment by dblock** [comment]
Yes, this one is basically deprecated.
